name: blank
on:
  push:
jobs:
  blank:
    runs-on: ubuntu-latest
    steps:
      - name: MyCommands
        run: |
          RED='\033[0;31m'
          NC='\033[0m' # No Color
          printf "I ${RED}love${NC} Stack Overflow\n"
