name: blank
on:
  push:
jobs:
  blank:
    runs-on: ubuntu-latest
    steps:
      - name: MyCommands
        run: |
          echo "$(tput setaf 1)Red text $(tput setab 7)and white background$(tput sgr 0)"
