name: blank
on:
  push:
jobs:
  blank:
    runs-on: ubuntu-latest
    steps:
      - name: MyCommands
        run: |
          red=`tput setaf 1`
          green=`tput setaf 2`
          reset=`tput sgr0`
          echo "${red}red text ${green}green text${reset}"
